prima: update driver
prima: Add make entries for prima

Change-Id: I92be01fb92c47d4d411455236e27c7545c4daafa

prima: Lower Kernel version for 6 arguments cfg80211_disconnected

* Our kernel is properly patched for this, see:
  cfg80211: properly send NL80211_ATTR_DISCONNECTED_BY_AP in disconnect

Change-Id: I88b323f1a5415974321588c21fbf7b491781d2f6

Read WLAN MAC addresses from UTAG

Merged Original CR's to have single commit:
(CR) Read WiFi MACs from bootargs
(CR) Handle inter MAC separator in utags

Factory sets 2 WiFi MACs as boot params. This code change
reads WiFi MACs from bootparams device tree node and
generates two other MACs by setting locally administrated
bit. Order of MAC addresses is MAC1, MAC2, GENERATED1, and
GENERATED2. From here on we don't read MAC addresses from
NV bin file.
Also handle cases none, comma and hypen as separator

Change-Id: Ied2bddaaef14b0849e3f8adc57ef9e14754166f5
Reviewed-on: http://gerrit.mot.com/833472
SLTApproved: Slta Waiver <sltawvr@motorola.com>
SME-Granted: SME Approvals Granted
Tested-by: Jira Key <jirakey@motorola.com>
Reviewed-by: Ishwara J A <ishwara@motorola.com>
Reviewed-by: Binesh Balasingh <binesh@motorola.com>
Submit-Approved: Jira Key <jirakey@motorola.com>

Wifi MAC address different from utags

Recent QC change of returning on param check fail is conflicting
with MOTO_UTAGS_MAC implementation. Remove that check here as
we are anyhow doing it before using it.

Change-Id: I0bf89d08a422f7f2e97bb8ef2deacfcc65a464e6
Reviewed-on: https://gerrit.mot.com/1177138
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Prashanth Chakravarthy <a19110@motorola.com>
Submit-Approved: Jira Key

Update OUI for WiFi fallback MAC address

Existing OUI in fallback is not from Moto. This is corrected
with this change, now using a Motorola OUI.

This will only affect the Fallback Mac address generated by the serial
number of the device.

Change-Id: Ib3d5aefd3e49c2f0b81d9c67352743d3a48eb4b4
Reviewed-on: https://gerrit.mot.com/1127704
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Prashanth Chakravarthy <a19110@motorola.com>
Submit-Approved: Jira Key

Driver blocking scans while on BT call

Allos wifi scans during BT sco call as is the case in titan/Condor/victara
SR 01884803.

Change-Id: Ie1f3e8202929d16a4b842a07f79231177446d1a6
Reviewed-on: http://gerrit.mot.com/706275
SLTApproved: Slta Waiver <sltawvr@motorola.com>
Tested-by: Jira Key <jirakey@motorola.com>
Reviewed-by: Binesh Balasingh <binesh@motorola.com>
Submit-Approved: Jira Key <jirakey@motorola.com>
Reviewed-on: http://gerrit.mot.com/838719
SME-Granted: SME Approvals Granted
Reviewed-by: Prashanth Chakravarthy <a19110@motorola.com>

Prop-(CR) Country specific NV file

Read NV.bin file from platform driver

Change-Id: I021903026f18e87144c3d501ae6613e087d2108b
Reviewed-on: http://gerrit.mot.com/842818
SLTApproved: Slta Waiver <sltawvr@motorola.com>
SME-Granted: SME Approvals Granted
Tested-by: Jira Key <jirakey@motorola.com>
Reviewed-by: Thai Leav <w18918@motorola.com>
Reviewed-by: Binesh Balasingh <binesh@motorola.com>
Submit-Approved: Jira Key <jirakey@motorola.com>
(cherry picked from commit 3cb9455d3bd1ac963dff7d614be6c407eeeda419)
Reviewed-on: http://gerrit.mot.com/843361
Reviewed-by: Navya Vijayan <navya@motorola.com>
SLTApproved: Sindhu C <a12924@motorola.com>
Reviewed-on: http://gerrit.mot.com/868692
Reviewed-by: Prashanth Chakravarthy <a19110@motorola.com>

staging: prima: Add Kconfig entry for TDLS

Change-Id: I670c8d7eb24de9f431d8dd89a8694fa216f4f9ff
Signed-off-by: Albert I <krascgq@outlook.co.id>

staging: prima: Fix non-debug build and switch to it

Enable the forward declaration of debug functions in non-debug
builds and disable a piece of code used only to print some info.
-Wno-unused-variable is now required because of all the variables
used in debug functions that aren't left out in non-debug builds.

Change-Id: I7069f8859e4965ee82ce65c29c35349c887fd673
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: overwrite mac address if config file exists

Modified from qcacld-2.0
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/qcacld-2.0/tree/CORE/HDD/src/wlan_hdd_main.c?h=LA.BR.1.3.6.c1-00810-8976.0

Change-Id: Ie1b7fb4e8a37595786c15a444d4e588cf0fdb58a
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Convert -Wno-maybe-uninitialized to cc-disable-warning call

clang doesn't support this flag...

warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]

Change-Id: I488ba044a23da5c06730ebe31b50ccd28ea0c8ae
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Kbuild: Disable some of clang warnings

Change-Id: I5e505d2be67f4bc42693c3a1dd28d5286cbd1126
[v2: Only use cc-name guard on array-bounds since it's used by GCC too]
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Remove unnecessary brackets

* Silence clang's parentheses-equality warnings

Change-Id: I441e51e7dd9a9aaf3d3f55c5c4b006dda8762ee8
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Fix for loop has empty body

Silence these warnings:

../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4096:43: error: for loop has empty body [-Werror,-Wempty-body]
   for (ptr = str; i_isspace(*ptr); ptr++);
                                          ^
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4096:43: note: put the semicolon on a separate line to silence this warning
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4105:48: error: for loop has empty body [-Werror,-Wempty-body]
   for (; ptr != str && i_isspace(*ptr); ptr--);
                                               ^
../drivers/staging/prima/CORE/HDD/src/wlan_hdd_cfg.c:4105:48: note: put the semicolon on a separate line to silence this warning

Signed-off-by: khusika <khusikadhamar@gmail.com>
[krasCGQ: Little fix to commit message]
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Resolved indentation warnings detected by Linaro GCC 6.4.1

* Using latest 2018.05 prebuilt release from releases.linaro.org.

Change-Id: Ic952acd31549d8d2e197c50af7c0329fc22ee238
Signed-off-by: Albert I <krascgq@outlook.co.id>

prima: Fix unreachable switch statement warning

Signed-off-by: Harsh Shandilya <harsh@prjkt.io>
Signed-off-by: Albert I <krascgq@outlook.co.id>

Signed-off-by: ronaxdevil <pratabidya.007@gmail.com>